version: '3.8'
services:
  nginx: 
    image: nginx:alpine
    ports:
     - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx.conf:ro
    depends_on:
      - web
  web:
    image: 24024102/my-first-pipeline:latest
    expose:
      - "80"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=mydatabase
      - DB_USER=admin
      - DB_PASSWORD=root
    deploy:
       replicas: 3
       resources:
         limits: 
          cpus: "0.5"
          memory: 128M


  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d mydatabase"]
      interval: 5s
      timeout: 5s
      retries: 5
   
volumes:
  pgdata:
   